# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.disksize.size = '100GB'

    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false
    end
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 10240
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
      vb.name = "dev-ubuntu-lts"
    end

    config.vm.provision "apt-sources", type: "shell", path: "provision/install-tools.sh"
    config.vm.provision "docker", type: "shell", path: "provision/install-docker.sh"
    config.vm.provision "mssql-odbc", type: "shell", path: "provision/install-python.sh"
  end
